{:status {:code 200, :msg "OK",
          :protocol "HTTP/1.1",
          :major 1, :minor 1},
 :headers {:cache-control "no-cache, no-store, must-revalidate, pre-check=0, post-check=0",
           :content-length "2448", :content-type "application/json;charset=utf-8",
           :date "Fri, 05 Jul 2013 15:28:18 GMT",
           :expires "Tue, 31 Mar 1981 05:00:00 GMT",
           :last-modified "Fri, 05 Jul 2013 15:28:18 GMT",
           :pragma "no-cache", :server "tfe",
           :set-cookie ["lang=en" "guest_id=v1%3A137303809894744966; Domain=.twitter.com; Path=/; Expires=Sun, 05-Jul-2015 15:28:18 UTC"],
           :status "200 OK", :x-access-level "read", :x-frame-options "SAMEORIGIN", :x-rate-limit-limit "180", :x-rate-limit-remaining "178",
           :x-rate-limit-reset "1373038905", :x-transaction "e381d793d112d0b5", :x-xss-protection "1; mode=block"},
 :body {:status {:favorite_count 36,
                 :entities {:hashtags [], :symbols [], :urls [{:url "http://t.co/Mn3X1mf8kB",
                                                               :expanded_url "http://goo.gl/JFA1K",
                                                               :display_url "goo.gl/JFA1K", :indices [111 133]}], :user_mentions []},
                 :text "Will Slovakia become the next hot e-country? Watch the spirited Hangouts discussion on the Google Europe Blog: http://t.co/Mn3X1mf8kB",
                 :retweet_count 75, :coordinates nil, :possibly_sensitive false, :in_reply_to_status_id_str nil,
                 :contributors nil, :in_reply_to_user_id_str nil, :id_str "352914085513396225", :in_reply_to_screen_name nil,
                 :retweeted false, :truncated false, :created_at "Thu Jul 04 22:17:29 +0000 2013", :lang "en", :geo nil,
                 :place nil, :in_reply_to_status_id nil, :favorited false, :source "web", :id 352914085513396225,
                 :in_reply_to_user_id nil},
        :profile_use_background_image true, :follow_request_sent false,
        :entities {:url {:urls [{:url "http://t.co/1juYtOv5Vo", :expanded_url "http://www.google.com",
                                 :display_url "google.com", :indices [0 22]}]},
                   :description {:urls []}},
        :default_profile false, :profile_sidebar_fill_color "EBEFF9", :protected false, :following false,
        :profile_background_image_url "http://a0.twimg.com/profile_background_images/703631651/1942e596ac2ecb5e10b07093e420dfa9.png",
        :default_profile_image false, :contributors_enabled false, :favourites_count 128, :time_zone "Pacific Time (US & Canada)",
        :name "A Googler",
        :id_str "20536157", :listed_count 82224, :utc_offset -28800, :profile_link_color "0000CC",
        :profile_background_tile true,
        :location "Mountain View, CA",
        :statuses_count 4302,
        :followers_count 6330412,
        :friends_count 396,
        :profile_banner_url "https://pbs.twimg.com/profile_banners/20536157/1352151937",
        :created_at "Tue Feb 10 19:14:39 +0000 2009", :lang "en", :profile_sidebar_border_color "FFFFFF",
        :url "http://t.co/1juYtOv5Vo",
        :notifications false, :profile_background_color "FFFFFF",
        :geo_enabled true, :profile_image_url_https "https://si0.twimg.com/profile_images/2504370963/6u5qf6cl9jtwew6poxcj_normal.png",
        :is_translator false, :profile_image_url "http://a0.twimg.com/profile_images/2504370963/6u5qf6cl9jtwew6poxcj_normal.png",
        :verified true,
        :id 20536157,
        :profile_background_image_url_https "https://si0.twimg.com/profile_background_images/703631651/1942e596ac2ecb5e10b07093e420dfa9.png",
        :description "News and updates from Google",
        :profile_text_color "000000", :screen_name "google"}}
