{:status {:code 200, :msg "OK",
          :protocol "HTTP/1.1", :major 1, :minor 1},
 :headers {:cache-control "no-cache, no-store, must-revalidate, pre-check=0, post-check=0",
           :content-length "2287", :content-type "application/json;charset=utf-8", :date "Fri, 05 Jul 2013 15:26:45 GMT",
           :expires "Tue, 31 Mar 1981 05:00:00 GMT", :last-modified "Fri, 05 Jul 2013 15:26:45 GMT", :pragma "no-cache",
           :server "tfe", :set-cookie ["lang=en" "guest_id=v1%3A137303800541742730; Domain=.twitter.com; Path=/; Expires=Sun, 05-Jul-2015 15:26:45 UTC"],
           :status "200 OK", :x-access-level "read", :x-frame-options "SAMEORIGIN", :x-rate-limit-limit "180",
           :x-rate-limit-remaining "179", :x-rate-limit-reset "1373038905", :x-transaction "5751479f293053ef",
           :x-xss-protection "1; mode=block"},
 :body {:status {:favorite_count 2,
                 :entities {:hashtags [], :symbols [],
                            :urls [{:url "http://t.co/7DXQqxLBTx",
                                    :expanded_url "http://bit.ly/14hdWrQ",
                                    :display_url "bit.ly/14hdWrQ", :indices [66 88]}], :user_mentions []},
                 :text "My second post on integrating Clojure, Noir and MongoDB on Heroku http://t.co/7DXQqxLBTx including local and remote integration tests",
                 :retweet_count 0, :coordinates nil, :possibly_sensitive false, :in_reply_to_status_id_str nil,
                 :contributors nil, :in_reply_to_user_id_str nil,
                 :id_str "342329773290311680", :in_reply_to_screen_name nil,
                 :retweeted false, :truncated false, :created_at "Wed Jun 05 17:19:12 +0000 2013",
                 :lang "en", :geo nil, :place nil, :in_reply_to_status_id nil,
                 :favorited false,
                 :source "<a href=\"http://twitter.com/tweetbutton\" rel=\"nofollow\">Tweet Button</a>",
                 :id 342329773290311680, :in_reply_to_user_id nil}, :profile_use_background_image true,
        :follow_request_sent false,
        :entities {:url {:urls [{:url "http://t.co/7yxenrx7q5",
                                 :expanded_url "http://emekamosanya.com",
                                 :display_url "emekamosanya.com", :indices [0 22]}]},
                   :description {:urls []}}, :default_profile true, :profile_sidebar_fill_color "DDEEF6",
        :protected false, :following false, :profile_background_image_url "http://a0.twimg.com/images/themes/theme1/bg.png",
        :default_profile_image false,
        :contributors_enabled false, :favourites_count 0, :time_zone "London",
        :name "Emeka Mosanya",
        :id_str "19400021", :listed_count 1, :utc_offset 0, :profile_link_color "0084B4", :profile_background_tile false,
        :location "London", :statuses_count 61, :followers_count 58, :friends_count 96, :created_at "Fri Jan 23 16:09:46 +0000 2009", :lang "en",
        :profile_sidebar_border_color "C0DEED", :url "http://t.co/7yxenrx7q5", :notifications false,
        :profile_background_color "C0DEED",
        :geo_enabled false, :profile_image_url_https "https://si0.twimg.com/profile_images/605965984/IMG_0215_normal.JPG",
        :is_translator false, :profile_image_url "http://a0.twimg.com/profile_images/605965984/IMG_0215_normal.JPG",
        :verified false, :id 19400021, :profile_background_image_url_https "https://si0.twimg.com/images/themes/theme1/bg.png",
        :description "", :profile_text_color "333333",
        :screen_name "EmekaMosanya"}}

